'use client'

import { useState, useEffect } from 'react'
import { createUsername } from '@/app/actions/auth'
import { generateUsername } from '@/lib/username-generator'

interface UsernameSetupModalProps {
  userId: string
  onComplete: () => void
}

export function UsernameSetupModal({ userId, onComplete }: UsernameSetupModalProps) {
  const [username, setUsername] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [autoGenerated, setAutoGenerated] = useState(false)

  // Auto-generate username on mount
  useEffect(() => {
    const generated = generateUsername()
    setUsername(generated)
    setAutoGenerated(true)
  }, [])

  const handleGenerateNew = () => {
    const generated = generateUsername()
    setUsername(generated)
    setAutoGenerated(true)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!username.trim()) {
      setError('Username is required')
      return
    }

    try {
      setLoading(true)
      setError('')

      const result = await createUsername({
        userId,
        username: username.trim(),
      })

      if (result.success) {
        onComplete()
      }
    } catch (err: any) {
      setError(err.message || 'Failed to create username')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-dark-card border border-dark-border rounded-2xl w-full max-w-md">
        <div className="p-6 space-y-4">
          <h2 className="text-2xl font-bold">Your Anonymous Username</h2>
          <p className="text-sm text-gray-400">
            We've generated a unique username for you. You can regenerate or customize it.
          </p>

          {error && (
            <div className="p-3 bg-error/20 border border-error text-error rounded-lg text-sm">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-gray-400">@</span>
                <input
                  type="text"
                  value={username}
                  onChange={(e) => {
                    setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9]/g, ''))
                    setAutoGenerated(false)
                    setError('')
                  }}
                  placeholder="username"
                  disabled={loading}
                  maxLength={20}
                  minLength={3}
                  pattern="[a-z0-9]+"
                  className="flex-1 bg-dark-secondary border border-dark-border rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-primary transition disabled:opacity-50"
                />
                <button
                  type="button"
                  onClick={handleGenerateNew}
                  disabled={loading}
                  className="px-3 py-3 bg-dark-secondary border border-dark-border rounded-lg hover:border-primary transition disabled:opacity-50"
                  title="Generate new username"
                >
                  🎲
                </button>
              </div>
              <p className="text-xs text-gray-400">
                {username.length}/20 characters • Letters and numbers only
                {autoGenerated && <span className="ml-2 text-primary">✨ Auto-generated</span>}
              </p>
            </div>

            <button
              type="submit"
              disabled={!username.trim() || username.length < 3 || loading}
              className="w-full btn-primary py-3 font-bold disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Creating...' : 'Continue'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}

